In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
#using Empty
a = torch.empty(2,3 )

In [8]:
# check type
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# using ones
torch.ones(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
# using rand
torch.rand(2,3)

tensor([[0.2169, 0.4133, 0.5729],
        [0.6954, 0.7267, 0.3299]])

In [13]:
# use of seed
torch.rand(2,3)

tensor([[0.4722, 0.0390, 0.9564],
        [0.9831, 0.9439, 0.1489]])

In [14]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes in Pytorch:--

In [22]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[    139340881128848,     139340881128848,                   0],
        [                  0,                   0, 7310593858020254331]])

In [25]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types:-

In [31]:
# find data type
x.dtype

torch.int64

In [32]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [35]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [38]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [39]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [40]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [41]:
c = torch.tensor([1, -2, 3, -4])

In [42]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [45]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp
torch.clamp(d, min=2, max=5)

tensor([2.0000, 2.3000, 3.7000, 4.4000])

### 3. Reduction operation

In [50]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [52]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [53]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [54]:
torch.median

<function torch._VariableFunctionsClass.median>

In [55]:
torch.median(e)

tensor(0.)

In [56]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [57]:
# product
torch.prod(e)

tensor(0.)

In [58]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [59]:
# variance
torch.var(e)

tensor(19.6000)

In [60]:
# argmax
torch.argmax(e)

tensor(5)

In [61]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [62]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [63]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [64]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [65]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [66]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [67]:
# determinant
torch.det(h)

tensor(-110.)

In [68]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [69]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [70]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [71]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [72]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [73]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [74]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [75]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [76]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [77]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [78]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [79]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [80]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [81]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [82]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [83]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [84]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [85]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [86]:
b = a

In [87]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [88]:
a[0][0] = 0

In [89]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [90]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [91]:
id(a)

139336449217296

In [92]:
id(b)

139336449217296

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [95]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [98]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [99]:
id(a)

139336449217296

In [101]:
id(b)

139336449217584

## Tensor Operation on GPU:-

In [102]:
torch.cuda.is_available()

True

In [103]:
device = torch.device('cuda')

In [105]:
## Creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [106]:
# Moving an existing tensor to GPU

a=torch.rand((2,3))
a.to(device)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]], device='cuda:0')

In [107]:
b=a.to(device)

## Reshaping Tensors

Reshaping a tensor changes its view without changing the data. This is useful when you need to change the dimensions of a tensor for operations like matrix multiplication or convolutional layers.

In [ ]:
# Create a tensor
x = torch.arange(12)
print("Original tensor:")
print(x)
print("Shape:", x.shape)

### `reshape()` and `view()`

`reshape()` and `view()` are used to change the shape of a tensor. `view()` requires the new shape to be compatible with the original shape (same number of elements), and it shares the same underlying data as the original tensor. `reshape()` can sometimes return a copy of the data, especially if the tensor is not contiguous in memory. For simple reshaping, they often behave similarly.

In [ ]:
# Reshape the tensor into a 3x4 matrix
reshaped_x = x.reshape(3, 4)
print("\nReshaped tensor (3x4):")
print(reshaped_x)
print("Shape:", reshaped_x.shape)

# Reshape using -1 to infer a dimension
reshaped_x_inferred = x.reshape(-1, 3)
print("\nReshaped tensor (inferred columns):")
print(reshaped_x_inferred)
print("Shape:", reshaped_x_inferred.shape)

# Using view (will also share the underlying data)
viewed_x = x.view(4, 3)
print("\nViewed tensor (4x3):")
print(viewed_x)
print("Shape:", viewed_x.shape)

# Modifying the viewed tensor affects the original
viewed_x[0, 0] = 99
print("\nOriginal tensor after modifying viewed_x:")
print(x)

print("\nViewed tensor after modifying viewed_x:")
print(viewed_x)

### `squeeze()` and `unsqueeze()`

`squeeze()` removes dimensions of size 1 from the tensor's shape.
`unsqueeze()` adds a dimension of size 1 at a specified position.

In [ ]:
# Create a tensor with singleton dimensions
y = torch.zeros(1, 2, 1, 3, 1)
print("Original tensor y:")
print(y)
print("Shape:", y.shape)

# Squeeze the tensor
squeezed_y = y.squeeze()
print("\nSqueezed tensor y:")
print(squeezed_y)
print("Shape:", squeezed_y.shape)

# Squeeze a specific dimension
squeezed_dim_y = y.squeeze(2)
print("\nSqueezed tensor y (dim 2):")
print(squeezed_dim_y)
print("Shape:", squeezed_dim_y.shape)

# Unsqueeze the tensor
unsqueezed_y = squeezed_y.unsqueeze(0)
print("\nUnsqueezed tensor (dim 0):")
print(unsqueezed_y)
print("Shape:", unsqueezed_y.shape)

# Unsqueeze another dimension
unsqueezed_dim_y = squeezed_y.unsqueeze(-1)
print("\nUnsqueezed tensor (dim -1):")
print(unsqueezed_dim_y)
print("Shape:", unsqueezed_dim_y.shape)

### `transpose()` and `permute()`

`transpose()` swaps two dimensions of a tensor.
`permute()` allows you to reorder the dimensions of a tensor arbitrarily by providing the desired order of dimensions.

In [ ]:
# Create a 3D tensor
z = torch.randn(2, 3, 4)
print("Original tensor z:")
print(z)
print("Shape:", z.shape)

# Transpose dimensions 0 and 1
transposed_z = torch.transpose(z, 0, 1)
print("\nTransposed tensor z (dim 0 and 1 swapped):")
print(transposed_z)
print("Shape:", transposed_z.shape)

# Permute dimensions
permuted_z = z.permute(2, 0, 1) # move dim 2 to first position, dim 0 to second, dim 1 to third
print("\nPermuted tensor z (dims reordered):")
print(permuted_z)
print("Shape:", permuted_z.shape)

## NumPy and PyTorch Interaction

PyTorch tensors can be easily converted to NumPy arrays and vice versa. This interoperability is very useful for integrating with other Python libraries that use NumPy, such as scikit-learn for data preprocessing or matplotlib for plotting.

### Converting from PyTorch Tensor to NumPy Array

In [108]:
import torch
import numpy as np

# Create a PyTorch tensor
torch_tensor = torch.ones(5)
print("PyTorch Tensor:")
print(torch_tensor)
print("Type:", type(torch_tensor))

# Convert to NumPy array
numpy_array = torch_tensor.numpy()
print("\nNumPy Array:")
print(numpy_array)
print("Type:", type(numpy_array))

PyTorch Tensor:
tensor([1., 1., 1., 1., 1.])
Type: <class 'torch.Tensor'>

NumPy Array:
[1. 1. 1. 1. 1.]
Type: <class 'numpy.ndarray'>


### Converting from NumPy Array to PyTorch Tensor

In [109]:
# Create a NumPy array
numpy_array_2 = np.zeros(5)
print("NumPy Array:")
print(numpy_array_2)
print("Type:", type(numpy_array_2))

# Convert to PyTorch tensor
torch_tensor_2 = torch.from_numpy(numpy_array_2)
print("\nPyTorch Tensor:")
print(torch_tensor_2)
print("Type:", type(torch_tensor_2))

NumPy Array:
[0. 0. 0. 0. 0.]
Type: <class 'numpy.ndarray'>

PyTorch Tensor:
tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
Type: <class 'torch.Tensor'>


### Important Note on Sharing Memory

When converting a CPU-based PyTorch tensor to a NumPy array using `.numpy()`, the resulting NumPy array will share the same underlying memory with the tensor. This means that changing the values in one will affect the other.

However, this is not the case for tensors on the GPU. When you convert a GPU tensor to NumPy, it will create a copy of the data on the CPU.

In [110]:
# Demonstrate shared memory on CPU
cpu_tensor = torch.ones(3)
cpu_numpy = cpu_tensor.numpy()

print("Original CPU Tensor:", cpu_tensor)
print("Original CPU NumPy Array:", cpu_numpy)

# Modify the NumPy array
cpu_numpy[0] = 100

print("\nCPU Tensor after modifying NumPy array:", cpu_tensor)
print("CPU NumPy Array after modifying NumPy array:", cpu_numpy)

Original CPU Tensor: tensor([1., 1., 1.])
Original CPU NumPy Array: [1. 1. 1.]

CPU Tensor after modifying NumPy array: tensor([100.,   1.,   1.])
CPU NumPy Array after modifying NumPy array: [100.   1.   1.]


In [111]:
# Demonstrate copying for GPU tensors
if torch.cuda.is_available():
    gpu_tensor = torch.ones(3).to('cuda')
    # Converting to NumPy from GPU requires moving to CPU first
    gpu_numpy = gpu_tensor.cpu().numpy()

    print("\nOriginal GPU Tensor:", gpu_tensor)
    print("Original GPU NumPy Array:", gpu_numpy)

    # Modify the NumPy array (this will NOT affect the GPU tensor)
    gpu_numpy[0] = 200

    print("\nGPU Tensor after modifying NumPy array:", gpu_tensor)
    print("GPU NumPy Array after modifying NumPy array:", gpu_numpy)
else:
    print("\nGPU not available. Cannot demonstrate GPU tensor to NumPy conversion.")


Original GPU Tensor: tensor([1., 1., 1.], device='cuda:0')
Original GPU NumPy Array: [1. 1. 1.]

GPU Tensor after modifying NumPy array: tensor([1., 1., 1.], device='cuda:0')
GPU NumPy Array after modifying NumPy array: [200.   1.   1.]
